version: 0.2
env:
  parameter-store:
    LOGIN: LOGIN
    HOST: HOST
    Organization: Organization
    Project: Project
    #CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
    - cp ./settings.xml /root/.m2/settings.xml
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nervos-core --domain-owner 593572207657 --region us-east-1 --query authorizationToken --output text`
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq curl unzip
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12-bin.tar.gz
      - tar xzvf apache-maven-3.9.12-bin.tar.gz
      - export PATH=$PWD/apache-maven-3.9.12/bin:$PATH
      - mvn -version
  build:
    commands:
      - mvn test
      - mvn checkstyle:checkstyle
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ -Dsonar.junit.reportsPath=target/surefire-reports/ -Dsonar.jacoco.reportsPath=target/jacoco.exec -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
      - sleep 15
      - curl -f https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json || echo '{"projectStatus":{"status":"UNKNOWN"}}' > result.json
      - cat result.json
      - STATUS=$(jq -r '.projectStatus.status // "UNKNOWN"' result.json 2>/dev/null || echo "UNKNOWN")
      - echo "Status is $STATUS"
      - '[ "$STATUS" = "ERROR" ] && exit 1 || exit 0'