#!/bin/bash
## Worker node initialization script
## Runs after bootstrap.sh completes on kworker1 and kworker2

# file copy to join nodes
echo "[TASK 1] Join node to Kubernetes Cluster"
cp /vagrant/joincluster.sh /joincluster.sh
bash /joincluster.sh

# Copy the join command generated by kubeadm on kmaster
# Uses root password set in bootstrap.sh (kubeadmin)
# kmaster.example.com resolves via /etc/hosts set in bootstrap.sh
sshpass -p "kubeadmin" scp -o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kmaster.example.com:/joincluster.sh /joincluster.sh 2>/dev/null

# --- printing error ---
#sshpass -p "kubeadmin" scp -o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kmaster.example.com:/joincluster.sh /joincluster.sh
# Execute the join command to register this node with the cluster
bash /joincluster.sh >/dev/null 2>&1
