#!/bin/bash
## Worker node initialization script
## Runs after bootstrap.sh completes on kworker1 and kworker2

echo "[TASK 1] Join node to Kubernetes Cluster"
# Install sshpass to allow password-based scp without interaction
apt install -qq -y sshpass >/dev/null 2>&1

# Copy the join command generated by kubeadm on kmaster
# Uses root password set in bootstrap.sh (kubeadmin)
# kmaster.example.com resolves via /etc/hosts set in bootstrap.sh
# sshpass -p "kubeadmin" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kmaster.example.com:/joincluster.sh /joincluster.sh 2>/dev/null
# printing error
sshpass -p "kubeadmin" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kmaster.example.com:/joincluster.sh /joincluster.sh

# Execute the join command to register this node with the cluster
bash /joincluster.sh >/dev/null 2>&1
