Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 900
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.synced_folder "..", "/k8s-javaApp"

  config.vm.define "kmaster", primary: true do |kmaster|
    kmaster.vm.box = "ubuntu/jammy64"
    kmaster.vm.network "private_network", ip: "192.168.33.2"
    kmaster.vm.hostname = "kmaster"
    kmaster.vm.provider "virtualbox" do |vb|
      vb.name = "kmaster"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
    end
    kmaster.vm.provision "shell", path: "bootstrap.sh"
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
    kmaster.vm.provision "shell", path: "set-kubeconfig.sh"
  end

  config.vm.define "kworker1" do |kworker1|
    kworker1.vm.box = "ubuntu/jammy64"
    kworker1.vm.network "private_network", ip: "192.168.33.3"
    kworker1.vm.hostname = "kworker1"
    kworker1.vm.provider "virtualbox" do |vb|
      vb.name = "kworker1"
      vb.memory = 3072
      vb.cpus = 2
    end
    kworker1.vm.provision "shell", path: "bootstrap.sh"
    kworker1.vm.provision "shell", path: "bootstrap_kworker.sh"
  end

  config.vm.define "kworker2" do |kworker2|
    kworker2.vm.box = "ubuntu/jammy64"
    kworker2.vm.network "private_network", ip: "192.168.33.4"
    kworker2.vm.hostname = "kworker2"
    kworker2.vm.provider "virtualbox" do |vb|
      vb.name = "kworker2"
      vb.memory = 3072
      vb.cpus = 2
    end
    kworker2.vm.provision "shell", path: "bootstrap.sh"
    kworker2.vm.provision "shell", path: "bootstrap_kworker.sh"
  end
end
